# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190301_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
