# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190305_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(max_length=30),
        ),
    ]
