# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-26 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190305_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
