# Generated by Django 3.0.7 on 2020-06-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploaded_file',
        ),
    ]
